#!/bin/bash

remote="$1"
url="$2"
read local_ref local_sha remote_ref remote_sha


# Don't push if you have invalid error codes set
# NOTE: The check runs against your currently checked out code, even if you are
# trying to push a different branch
check_error_codes() {
    output=$(python buildscripts/errorcodes.py)
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
        echo "$output"
        echo -n "Error codes problem detected in currently checked out branch; "
        echo "aborting push. To push anyway use --no-verify"
        exit $RETVAL
    fi
}

# Lists the commit messages for the commits being pushed and promts the user for
# confirmation before pushing.
# NOTE: Getting the list of commits to be pushed can fail if the base commit on
# the remote isn't a direct ancestor of the commits staged in your local repo.
check_pending_commit_messages() {
    if [ "$local_sha" = "" ]
    then
        echo "No pending commits found!"
    else
        echo "Commits pending:"
        echo "$(git log --oneline $remote_sha..$local_sha)"
        echo ""

        exec < /dev/tty # eww
        read -p "Are you sure you want to push (y/n)? " choice

        case "$choice" in
            y|Y|yes|Yes|YES ) choice="yes";;
            n|N|no|No|NO ) choice="no";;
            * ) echo "invalid option: $choice"; exit 1;;
        esac

        if [ "$choice" = "no" ]
        then
            exit 1
        fi
    fi
}

# Don't push if we are in code freeze in the branch we're pushing to.
check_code_freeze() {

    branch=$(git name-rev --name-only $remote_ref)

    # Get the code freeze status
    freeze="`curl -fs https://s3.amazonaws.com/codefreeze/codefreeze.json`"
    if [ $? -ne 0 ]; then
        echo "I have no idea, sorry!"
        exit 1
    fi

    # Is this branch frozen?
    frozen="`echo "$freeze" | grep "$branch" | grep "Yes" | cut -d: -f1`"

    if [ -n "$frozen" ]; then
        if [ "$PUSH_ANYWAY" == "yes" ]; then
            echo "WARNING: force-pushing onto frozen branch ${branch}..."
            return
        else
            echo
            echo "WARNING: branch $branch is in code freeze. You can still push your changes IIF:"
            echo "- you're fixing a broken build, or"
            echo "- you have approval to push from your lead"
            echo
            echo "Run:"
            echo "  PUSH_ANYWAY=yes git push"
            echo
            exit 1
        fi
    fi
}

# check_error_codes
# check_code_freeze
check_pending_commit_messages
