#!/bin/bash

check_lint() {
    files=$(git diff-index --name-only HEAD)
    if [ -z $files ]; then
        echo "Found no modified files, skipping lint check"
        return
    fi
    output=$(xargs python buildscripts/lint.py $files)
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
        echo "$output"
        echo -n "Lint problems detected, aborting commit.  "
        echo "To commit anyway use --no-verify"
        exit 1
    fi
}

# Fix 0 assert codes before comitting.
fix_error_codes() {
    output=$(python buildscripts/errorcodes.py --fix)
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
        echo "$output"
        echo -n "Error codes problem detected in currently checked out branch; "
        echo "aborting commit. To commit anyway use --no-verify"
        exit $RETVAL
    fi
}

check_lint
#fix_error_codes #useless b/c the change happens after the commit
exit 0
